### PR TITLE
changes to background colour

### PR DESCRIPTION
**Pull request by sashaward**
Removed vertical height of container so that background colour covered all elements

### CODE REVIEW

**Comment by sashaward** [comment]
@clmntnbrn @JunBadger ready for review

**Comment by clmntnbrn** [comment]
@sashaward Super! Just need to add `2rem` padding to the bottom of the `.container` I think 😉

**Comment by sashaward** [comment]
will do!

**Comment by sashaward** [comment]
@clmntnbrn @JunBadger ready for review

**Review by clmntnbrn — APPROVED** [review]

**Comment by clmntnbrn** [comment]
👍  merge away @sashaward!

**Pull request merged**
